### ISSUE TITLE
May I get a full manual about jQueryGantt?

### ISSUE THREAD

**Issue by liangzhengai** [robicch/jQueryGantt#30]
Your product, jQueryGantt is the best among ganntt based on jQuery.
But mannual is insufficient so there are some problems in using.
Can you help me?
Thank you.

**Comment by robicch** [comment]
yes, post your question here.

**Comment by layinka** [comment]
I am having the exact same problem, i cannot get it to run, for example i am trying to use it in asp.net mvc project, but i found out that so many things are interrelated that its difficult to decouple it and assemble it back
can you provide a tutorial stating what files should be added, in what order they should be added and how to initialise the gantt cchart ?
Also, there is a lot of conflicts if i use another jquery version.

i have copied the code as is(from the example) into my masterpage in asp.net mvc just to see it work,but its still not working, i have this error "Uncaught TypeError: Cannot use 'in' operator to search for 'marginTop' in undefined"

**Comment by robicch** [comment]
Hi Layinka
1) This component is JS based and it is (it could be) stand alone. You do not need any server to run, just a standard web page. 
2) there is nothing to "decouple". Include the .js files as in the gantt.html. There are only two possible interaction with the server: when your read the data and when you save it. In both cases you have to manage a single json object. 
3) this release uses an old jQuery (1.8) version. A new release for version 2 is ready and will be released asap.
4) If the gantt.html page works, your .net page have to work too.

This is a js component. There is no server interaction supplied, there are too many languages to care :-)
Everyone have to develop its server side part.

**Comment by layinka** [comment]
Hi, i understand that this is javascript based, what i am saying is every server side language/framework has ways they implement their own stuff,(including folder structure and all)
I have included the javascript files exactly as is on my page but yet its not working, first it had some issues with jquery version. i noticed that and changed to 1.8.
But i noticed it has some issues with path to the res folder, which i had to go and change because i am not using your exact directory structure, but i only saw that after having to go through all the javascript files.
i am just saying there might be a simpler tutorial.
I have still not gotten it to work and it doesnt show any error any longer on the chrome debugger so i dont even know why its not working.
I will still go through again and if i get it to work i will let you know.

Thanks for the great work and i hope i figure it out or the jquery 2 version comes out soon enough.

**Comment by robicch** [comment]
If you solve the issues with your framework you could contribute writing the tutorial for .net. 
The community will thank you ;-)

**Comment by layinka** [comment]
Hi,
Please if you dont mind, here is my generated html file, is it possible you
check and see if you can see whats wrong?

It should work if you out it in the same folder as the gantt.html file.

Thanks

On Tue, Feb 24, 2015 at 10:19 AM, Roberto Bicchierai <
notifications@github.com> wrote:

> If you solve the issues with your framework you could contribute writing
> the tutorial for .net.
> The community will thank you ;-)
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/robicch/jQueryGantt/issues/30#issuecomment-75722971>.
>



-- 
Olayinka Tanimomo (MCTS,CCNA)
Software/Web/Mobile Developer

**Comment by layinka** [comment]
Please if you dont mind, please help me check my generated file in this rar file http://1drv.ms/17SDFw2. (ProjectWorkSpace.html).

**Comment by robicch** [comment]
In your file templates are broken. 
It should be 
<div class="__template__" type=".."><!--  

--!></div>

and not

<div class="__template__" type="..">
<!--  

--!>
</div>


Cheers,

**Comment by layinka** [comment]
Ok, Thanks.
That fixed it.
