### ISSUE TITLE
 error in IE 11 getElementsByClassName

### ISSUE THREAD

**Issue by Edisson** [robicch/jQueryGantt#37]
Strange I have this error in Internet Explorer 11

it happens after execution 
taskBox.find(".linkHandleSVG").mousedown(function (e)..
in ganttDrawerSVG.js file

so seems linkHandleSVG doesn't support property or method getElementsByClassName.

could you help me.. might be some problem with migration on jquery 2.1.3 I use?

**Comment by robicch** [comment]
Yes, I have already solved this issue.
The problem is that jQuery used an optimezed query for searching classes (in particular using the method getElementsByClassName), that someone forget to implement in IE11 for SVG objects.

I worked around this using  
el.find("[class*=linkHandleSVG]")

instead of the buggy 
.find(".linkHandleSVG")

**Comment by Edisson** [comment]
oh it works! really, thanks!

**Comment by Patroklo** [comment]
Hi! First of all, thanks to @robicch for this awesome library!
In second place, I have just made a fork of this project and made a couple of changes to make the app compatible with IE11, right now I'm testing it but it seems that with a couple of little code lines I could make it. Feel free to download it in https://github.com/Patroklo/jQueryGantt

Can't promise a steady update of my fork, but if you send me a message via github or mail, I'll try to update  it asap with the main trunk.
