### ISSUE TITLE
Lazy loading

### ISSUE THREAD

**Issue by Edisson** [robicch/jQueryGantt#38]
It's only recent thoughts.. likely you don't have in plan to work it in practice.
it would be great to implement something like a lazy load of data in two cases:

1. load/draw tasks when we click "plus" in the dataTree and not all data at once.
because if there are a lot of tasks from server it takes time to put it all in diagram

2. loading/draw calendar only in certain interval and load more dates while scrolling.
when we have different projects are loaded with different date ranges it takes a huge time to draw several decades (of years)

I understand it's not easy to implement but I think it would be useful someday for anyone:)

**Comment by robicch** [comment]
Yeah, hard to develop.

1) you must load all task with dependencies, not only sub-trees. If you have deps between level it could be a nightmare :-)

2) this seems easier technically, but I cannot figure how to re-use the same rows for different tasks when you "pan". 

At glance seem that the features you are requesting fits better a viewer instead of an editor. 
Anyway there is a "sponsor" available?

**Comment by Edisson** [comment]
Really it's a nightmare, agree! 
But might be you will implement it for yourself anyhow, one way or another, it would be nice:)

yes it's mostly about viewer, right.

currently I'm satisfied with your component enough and keep embedding it in our web system:)

**Comment by Edisson** [comment]
If I know anything about "sponsor" I will let you know:)
